# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pickfish/bet_detail.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pickfish/bet_detail.proto',
  package='betDetail',
  serialized_pb='\n\x19pickfish/bet_detail.proto\x12\tbetDetail\"V\n\x07\x62\x65tData\x12\x11\n\ttimestamp\x18\x01 \x02(\x06\x12\x0b\n\x03\x62\x65t\x18\x02 \x02(\x07\x12\x0e\n\x06profit\x18\x03 \x02(\x0f\x12\x0b\n\x03tax\x18\x04 \x02(\x07\x12\x0e\n\x06\x66ishes\x18\x05 \x03(\x07\"1\n\tbetDetail\x12$\n\x08\x62\x65tDatas\x18\x01 \x03(\x0b\x32\x12.betDetail.betData')




_BETDATA = _descriptor.Descriptor(
  name='betData',
  full_name='betDetail.betData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='betDetail.betData.timestamp', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bet', full_name='betDetail.betData.bet', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='profit', full_name='betDetail.betData.profit', index=2,
      number=3, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tax', full_name='betDetail.betData.tax', index=3,
      number=4, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fishes', full_name='betDetail.betData.fishes', index=4,
      number=5, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=126,
)


_BETDETAIL = _descriptor.Descriptor(
  name='betDetail',
  full_name='betDetail.betDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='betDatas', full_name='betDetail.betDetail.betDatas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=128,
  serialized_end=177,
)

_BETDETAIL.fields_by_name['betDatas'].message_type = _BETDATA
DESCRIPTOR.message_types_by_name['betData'] = _BETDATA
DESCRIPTOR.message_types_by_name['betDetail'] = _BETDETAIL

class betData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BETDATA

  # @@protoc_insertion_point(class_scope:betDetail.betData)

class betDetail(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BETDETAIL

  # @@protoc_insertion_point(class_scope:betDetail.betDetail)


# @@protoc_insertion_point(module_scope)
