# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hot_write.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hot_write.proto',
  package='hot_write',
  serialized_pb='\n\x0fhot_write.proto\x12\thot_write\"B\n\rS_C_Hot_write\x12\x0f\n\x07\x41quatic\x18\x01 \x02(\x02\x12\x12\n\nUnderWater\x18\x02 \x02(\x02\x12\x0c\n\x04pump\x18\x03 \x02(\x02\"B\n\rC_S_Hot_write\x12\x0f\n\x07\x41quatic\x18\x01 \x02(\x02\x12\x12\n\nUnderWater\x18\x02 \x02(\x02\x12\x0c\n\x04pump\x18\x03 \x02(\x02*4\n\nMSG_HEADER\x12\x12\n\rC_S_HOT_WRITE\x10\x81@\x12\x12\n\rS_C_HOT_WRITE\x10\x82@')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='hot_write.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C_S_HOT_WRITE', index=0, number=8193,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_HOT_WRITE', index=1, number=8194,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=166,
  serialized_end=218,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
C_S_HOT_WRITE = 8193
S_C_HOT_WRITE = 8194



_S_C_HOT_WRITE = _descriptor.Descriptor(
  name='S_C_Hot_write',
  full_name='hot_write.S_C_Hot_write',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Aquatic', full_name='hot_write.S_C_Hot_write.Aquatic', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UnderWater', full_name='hot_write.S_C_Hot_write.UnderWater', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pump', full_name='hot_write.S_C_Hot_write.pump', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=96,
)


_C_S_HOT_WRITE = _descriptor.Descriptor(
  name='C_S_Hot_write',
  full_name='hot_write.C_S_Hot_write',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Aquatic', full_name='hot_write.C_S_Hot_write.Aquatic', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UnderWater', full_name='hot_write.C_S_Hot_write.UnderWater', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pump', full_name='hot_write.C_S_Hot_write.pump', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['S_C_Hot_write'] = _S_C_HOT_WRITE
DESCRIPTOR.message_types_by_name['C_S_Hot_write'] = _C_S_HOT_WRITE

class S_C_Hot_write(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_HOT_WRITE

  # @@protoc_insertion_point(class_scope:hot_write.S_C_Hot_write)

class C_S_Hot_write(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C_S_HOT_WRITE

  # @@protoc_insertion_point(class_scope:hot_write.C_S_Hot_write)


# @@protoc_insertion_point(module_scope)
